### ISSUE TITLE
User registration is still throwing either 500 server error OR some unknown error.

### ISSUE THREAD

**Issue by vy3191** [Build-Week-International-S-S-W/Backend#1]
Error: Actions may not have an undefined "type" property. Have you misspelled a constant? at dispatch (http://localhost:3000/static/js/0.chunk.js:87170:13) at http://localhost:3000/static/js/0.chunk.js:86764:17 at http://localhost:3000/static/js/0.chunk.js:86939:16 at dispatch (http://localhost:3000/static/js/0.chunk.js:87606:28) at http://localhost:3000/static/js/main.chunk.js:315:7
__proto__: Object
redux-logger.js:1  next state 
{usersRegister: {…}}

Link: API for user registration or signup
﻿
​

**Comment by FIOpwK** [comment]
I think Front-end is good on this now. Getting 201 as expected. feel free to close this ticket Oksana! Thank You again.
